"""Add metadata fields to wardrobe_items

Revision ID: 35e6b309653a
Revises: b38dfd83eb20
Create Date: 2025-11-05 19:36:58.659491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e6b309653a'
down_revision: Union[str, Sequence[str], None] = 'b38dfd83eb20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wardrobe_items', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('wardrobe_items', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('wardrobe_items', sa.Column('purchase_date', sa.String(), nullable=True))
    op.add_column('wardrobe_items', sa.Column('wear_count', sa.Integer(), nullable=True))
    op.add_column('wardrobe_items', sa.Column('last_worn_date', sa.String(), nullable=True))
    op.add_column('wardrobe_items', sa.Column('is_favorite', sa.Integer(), nullable=True))
    op.add_column('wardrobe_items', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wardrobe_items', 'tags')
    op.drop_column('wardrobe_items', 'is_favorite')
    op.drop_column('wardrobe_items', 'last_worn_date')
    op.drop_column('wardrobe_items', 'wear_count')
    op.drop_column('wardrobe_items', 'purchase_date')
    op.drop_column('wardrobe_items', 'price')
    op.drop_column('wardrobe_items', 'brand')
    # ### end Alembic commands ###
